MultiFabRegister: `throw` in get
BLAST-WarpX/warpx pull request #5356
Opened 2024-10-02 15:54 UTC by ax3l

Follow-up to #5230

- [x] Throw a runtime exception instead of returning a `nullptr` if a field is requested via the getter.
- [ ] update logic to ensure this passes all tests

2024-10-18 23:03 UTC, EZoni commented
Discussed with @RemiLehe offline:

The function `get_mr_levels_alldirs` fails by definition when we call it on coarse-patch MultiFabs, e.g., `current_cp`, because those are allocated only for on levels greater than level `0` while the function attempts to return all levels starting from `0`.

We will try to add to `get_mr_levels_alldirs` a function argument, e.g., `skip_level_0`, such that the function returns a `nullptr` for level `0` instead of calling the internal functions of the MultiFabRegister and throwing an exception.

2024-10-19 00:54 UTC, EZoni requested changes

2024-10-19 00:54 UTC, EZoni commented on Source/ablastr/fields/MultiFabRegister.cpp
>              return nullptr;
I think we can remove this:
```suggestion
            throw std::runtime_error("MultiFabRegister::get name does not exist in register: " + internal_name);
```

2024-10-19 00:54 UTC, EZoni commented on Source/ablastr/fields/MultiFabRegister.cpp
>              return nullptr;
I think we can remove this:
```suggestion
            throw std::runtime_error("MultiFabRegister::get name does not exist in register: " + internal_name);
```

2024-10-21 23:24 UTC, EZoni commented on Source/WarpX.cpp
> +        amrex::Print() << "allocate current_cp" << std::endl;
Debugging info left over by mistake:
```suggestion
```

2025-01-28 23:22 UTC, EZoni commented
@ax3l @RemiLehe 

Just a heads-up, I rebased and pushed a few more fixes since last week and this might be almost ready. Let's see the latest CI status after the last commit and move from there.

2025-01-29 00:51 UTC, EZoni commented
This is the only CI failure left after the last commit:
```
The following tests FAILED:
	417 - test_3d_effective_potential_electrostatic_picmi.run (Failed)
	418 - test_3d_effective_potential_electrostatic_picmi.analysis (Failed)
	419 - test_3d_effective_potential_electrostatic_picmi.checksum (Failed)
```
I will push a commit to try to fix the test.

2025-01-29 17:03 UTC, EZoni commented
@ax3l @lucafedeli88 @RemiLehe 

CI is green now and the PR is ready for review.

2025-01-29 18:09 UTC, ax3l reviewed
Excellent! Just a small Doxygen update needed and a few ideas for later improvements.

2025-01-29 18:09 UTC, ax3l commented on Source/BoundaryConditions/PML.cpp
> +    ablastr::fields::ScalarField pml_F_fp = (fields.has(FieldType::pml_F_fp, lev)) ? fields.get(FieldType::pml_F_fp, lev) : nullptr;
hehe, that's one way to quickly get the behavior in without changing downstream :D okok, nice idea and we can make this more robust later.

2025-01-29 18:09 UTC, ax3l commented on Source/ablastr/fields/MultiFabRegister.H
> +            bool skip_level_0=false
We need to add the new param `skip_level_0` in `@param` of the doxgen string.

2025-01-29 18:09 UTC, ax3l commented on Source/ablastr/fields/MultiFabRegister.H
> +            bool skip_level_0=false
We need to add the new param `skip_level_0` in `@param` of the doxgen string.

2025-01-29 18:09 UTC, ax3l commented on Source/ablastr/fields/MultiFabRegister.cpp
> +                field_on_level.push_back(nullptr);
Is pushing back a `nullptr` the clean approach or not pushing back anything (`skip` might imply either).
Then on the other hand, I assume if we move the level indexing on `skip` that can cause a lot of confusion, too (one argument to not use a `Vector` for the list of pointers.)

Thus, ok for me to keep as you suggest for now.

2025-01-29 18:12 UTC, ax3l commented on Source/ablastr/fields/MultiFabRegister.H
> +            bool skip_level_0=false
done.

2025-01-29 18:12 UTC, ax3l commented on Source/ablastr/fields/MultiFabRegister.H
> +            bool skip_level_0=false
done.

2025-01-29 19:04 UTC, EZoni approved these changes
@ax3l 

Thanks for reviewing my changes.

Yes, in some corner cases (e.g., F in the PML) I just pushed the issue to the next "layer". Those were changes that date back to last year, I might have been unsure about how to resolve those at the time.

I'll approve on my end and let @roelof-groenewald or @lucafedeli88 chime in further.

I would make sure that people have enough time to look at this PR and double check the changes, since they are not trivial.

2025-01-30 05:13 UTC, roelof-groenewald reviewed
The changes are fine, but I wonder if we can rename the `skip_level_0` variable to something else, maybe `skip_level_0_for_coarse_patch`. The reason I say that is if someone reads the code in the future, seeing just `skip_level_0 = true`, in something like `ComputeSpaceChargeField()` it could seem like the potential is not calculated for level 0 at all. Does that make sense?

2025-01-30 23:58 UTC, EZoni commented
Thanks, @roelof-groenewald. I renamed the variable to `skip_lev0_coarse_patch`, just to shorten the name as much as possible without missing any crucial component.

2025-01-31 02:12 UTC, ax3l commented
I think renaming in the usage code, `skip_lev0_coarse_patch` made sense.

In the `MultiFabRegister` class it does not make sense to me: this flag works for any patch, fine or coarse, if you pass it level 0 is skipped. I would thus suggest to keep `skip_level_0` as the argument name in `MultiFabRegister.H`/`.cpp` if that makes sense @EZoni @roelof-groenewald

2025-01-31 03:11 UTC, EZoni commented
Thanks, @ax3l.

My bad, I went through the renaming too fast. I agree that it would make sense to use two different names.

As for this,

> (Alternatively, do not add the new arg to the API at all and instead in user-code zero-out the 0-level coarse patch component on your `skip_lev0_coarse_patch` variable or even better, pass `skip_lev0_coarse_patch` to the call that should not process the level to be explicit. I am not sure how universally useful this argument addition in MultiFabRegister truly is, looks a bit hacky to me.)

I think I don't understand the suggestion. The reason for introducing the variable was that we have two methods, `get_mr_levels` and `get_mr_levels_alldirs`, that loop over all MR levels, and therefore we cannot call those methods on any coarse-patch MultiFab, e.g., `rho_cp`, because nothing is allocated for those MultiFabs on level 0. I think what I don't understand in the suggestion is what data we would "zero out": my understanding is that there would be no data to zero out because the underlying allocation is missing, since coarse-patch data is not allocated on level 0. I think this was @RemiLehe's and my understanding when we discussed what is summarized in https://github.com/ECP-WarpX/WarpX/pull/5356#issuecomment-2423349551 and came with the `skip_level_0` workaround.

2025-01-31 05:31 UTC, ax3l commented
Perfect.

Per last suggestion: oh yes, you are absolutely right that would not work 😂 ok, yes since this applies actually to all our cp, let's have it in the API (with the name back to the original).

2025-01-31 21:00 UTC, merged